#!/usr/bin/python

import os
import sys
import time
import argparse

from chase import pychase

def main():

    pc = pychase.PyChase()

    p = argparse.ArgumentParser(
            description=u"Imports all src.rpms into git and lookaside cache",
        )

    sp = p.add_subparsers()

    p_builds = sp.add_parser("buildinfo", help=u"gather build information for package(s)")
    p_builds.add_argument("pkgs", nargs='*', help=u"package list")
    p_builds.add_argument("tag", help=u"name of tag")
    p_builds.set_defaults(func=pc.do_buildinfo)

    p_failures = sp.add_parser("failed-builds", help=u"display failed builds for all packages within a tag")
    p_failures.add_argument("tag", help=u"name of tag")
    p_failures.set_defaults(func=pc.do_failed_pkgs)

    args = p.parse_args()
#    print "Args: %s" % str(args)

    args.func(args)

if __name__ == "__main__":
    raise SystemExit(main())
