#!/usr/bin/python

import os
import sys
import time
import argparse

from chase import pychase

def main():

    pc = pychase.PyChase()

    p = argparse.ArgumentParser(
            description=u"Imports all src.rpms into git and lookaside cache",
        )

    sp = p.add_subparsers()

    p_builds = sp.add_parser("buildinfo", help=u"gather build information from package(s)")
    p_builds.add_argument("pkgs", nargs='*', help=u"package list, if not provided, will use all packages")
    p_builds.add_argument("--tag", help=u"name of tag")
    p_builds.set_defaults(func=pc.do_buildinfo)

    args = p.parse_args()
#    print "Args: %s" % str(args)

    args.func(args)

if __name__ == "__main__":
    raise SystemExit(main())
